import { useState } from 'react';
import { BookOpen } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { ExamPractice } from './ExamPractice';
import { ProjectTool, toolNames } from '../data/projects';
import { GlossaryContent } from './Glossary';
import { FlowchartSequenceExample, FlowchartSymbolGuide } from './FlowchartLearnVisuals';

function MindMap({type}:{type:'library'|'tunnel'|'presentation'}) {
  const labels=type==='library'?['School festival','Activities','Audience','Resources','Music','Sport','Pupils','Families','Venue','Budget']:type==='tunnel'?['Build a club website','Discover','Plan','Review','Needs','Audience','Pages','Content','Test','Improve']:['Our news app','Read','Personalise','Get help','Headlines','Sport','Topics','Alerts','Contact','Accessibility'];
  const positions=[[325,32],[70,140],[325,140],[580,140],[15,252],[145,252],[270,252],[400,252],[525,252],[655,252]];
  return <svg className="learning-svg" viewBox="0 0 800 350" role="img" aria-label={`${type} mind map: ${labels.join(', ')}`}>
    <title>{type} mind map</title>{[[0,1],[0,2],[0,3],[1,4],[1,5],[2,6],[2,7],[3,8],[3,9]].map(([a,b])=><path key={`${a}-${b}`} d={`M${positions[a][0]+65},${positions[a][1]+44} L${positions[b][0]+65},${positions[b][1]}`} stroke="#8994b6" strokeWidth="3"/>)}
    {labels.map((l,i)=><g key={l} transform={`translate(${positions[i][0]},${positions[i][1]})`}><rect width="130" height="44" rx="18" fill={i===0?'#3d5ae0':i<4?'#dce4ff':'#e6f6f2'}/><text x="65" y="27" textAnchor="middle" fill={i===0?'#fff':'#172347'} fontSize="14" fontWeight="600">{l}</text></g>)}<text x="18" y="333" fontSize="15" fill="#465471">Central focus → main ideas → supporting details. Lines show relationships.</text>
  </svg>;
}
function WireframeExample(){return <div className="wire-example" role="img" aria-label="Three wireframe screens: Home links to Clubs; Clubs links to Club details, with back navigation.">{[['Home','School logo','Find a club →','Help'],['Clubs','Image placeholder','Music club →','← Home'],['Club details','Image placeholder','Join club','← Clubs']].map((screen,i)=><div className="wire-screen" key={i}><strong>{screen[0]}</strong><div className="wire-image">{screen[1]}</div><div className="wire-button">{screen[2]}</div><div className="wire-button">{screen[3]}</div></div>)}</div>;}
function Flyer({plan=false}:{plan?:boolean}){return <div className={`flyer-example ${plan?'flyer-plan':''}`} role="img" aria-label={plan?'Flyer visualisation plan with annotations for heading, images, details and footer':'Finished original school open evening flyer'}>{plan?<><div className="plan-heading">TITLE AREA</div><p>Annotation: 32-point bold heading; white on navy.</p><div className="wire-image">IMAGE / GRAPHIC AREA</div><p>Annotation: use a learning-themed graphic here.</p><div className="wire-button">DATE · TIME · LOCATION</div><p>Annotation: large, readable text; align to the left.</p><div className="wire-button">CONTACT / CALL TO ACTION</div><p>Annotation: contrasting footer with school contact.</p></>:<><span className="flyer-tag">EXPLORE · DISCOVER · CREATE</span><h3>SCHOOL<br/>OPEN EVENING</h3><BookOpen size={64} aria-label="Open book learning graphic"/><div className="flyer-panel">Meet our teachers.<br/>Explore our subjects.<br/>Find your next adventure.</div><strong>THURSDAY 15 OCTOBER<br/>4:30–7:00 PM</strong><p>Main hall · Example School</p><div className="flyer-footer">EVERYONE WELCOME<br/>Ask reception for details</div></>}</div>;}
export function LearningResources({tool}:{tool:ProjectTool}){
  const [type,setType]=useState<'library'|'tunnel'|'presentation'>('library');
  const [large,setLarge]=useState(false);
  return <section className={`learning-resources ${large?'resource-large':''}`}><h3>See an example: {toolNames[tool]}</h3><button className="btn btn-secondary btn-sm" aria-expanded={large} onClick={()=>setLarge(!large)}>{large?'Use normal size':'Enlarge examples'}</button>
    {tool==='mindmap'&&<><div className="project-actions">{(['library','tunnel','presentation'] as const).map(t=><button className={`btn ${type===t?'btn-primary':'btn-secondary'}`} key={t} aria-pressed={type===t} onClick={()=>setType(t)}>{t==='library'?'Library / reference':t==='tunnel'?'Tunnel timeline':'Presentation'}</button>)}</div><MindMap type={type}/><GlossaryContent><p>{type==='library'?'A reference mind map groups information so you can understand and revisit a topic.':type==='tunnel'?'A tunnel-timeline mind map focuses on achieving a goal or solving a problem. Its branches organise the work needed; it is not a detailed timetable.':'A presentation mind map organises ideas clearly for a target audience. Keep the main message easy to follow.'}</p></GlossaryContent></>}
    {tool==='flowchart'&&<><FlowchartSymbolGuide/><FlowchartSequenceExample/></>}
    {tool==='wireframe'&&<><WireframeExample/><GlossaryContent><p>The boxes show layout and placeholders. Labels and arrows explain navigation. This is a plan, not a working app; code is still needed to make its buttons function.</p></GlossaryContent></>}
    {tool==='visualisation'&&<><div className="resource-pair"><figure><Flyer plan/><figcaption>1. Annotated visualisation diagram: the plan</figcaption></figure><figure><Flyer/><figcaption>2. Finished flyer: the product (fictional event)</figcaption></figure></div><GlossaryContent><p>The annotation specifies design choices. The finished flyer applies the planned heading, information hierarchy and footer. A flyer is the product—not the name of the design tool.</p></GlossaryContent></>}
    {tool==='moodboard'&&<><div className="mood-example" role="img" aria-label="Sports campaign mood board with navy, lime and white colour swatches, bold typography and energetic keywords"><div style={{background:'#142343',color:'white'}}>Navy<br/>#142343</div><div style={{background:'#d5ef47'}}>Lime<br/>#D5EF47</div><div style={{background:'white'}}>White<br/>#FFFFFF</div><div className="mood-type">MOVE<br/>TOGETHER</div><div>Energetic · inclusive<br/>Bold · outdoors</div><div style={{fontFamily:'Georgia'}}>Typeface contrast<br/>Serif / sans-serif</div></div><p>A mood board communicates a visual direction, not the exact finished layout. Add your own or licensed photographs in the project editor to extend this colour-and-type example.</p></>}
    <details className="read-more"><summary>Read more: purpose, features and limitations</summary><GlossaryContent><ResourceNotes tool={tool}/></GlossaryContent></details>
  </section>;
}
function ResourceNotes({tool}:{tool:ProjectTool}) { const notes:Record<ProjectTool,string[]>={
  mindmap:['Purpose: organise ideas and reveal relationships. Start with a central focus, connect main categories and add sub-nodes for detail. Use keywords or short phrases rather than paragraphs.','A reference map helps summarise a topic; a tunnel-timeline map supports working towards a goal; a presentation map communicates organised ideas to an audience.','Advantage: branches make related ideas easier to see and update. Limitation: too many branches or long text can make the map crowded and hard to interpret.','Software: dedicated mind-mapping software or presentation software can create a mind map. Choose tools that make connecting and rearranging ideas easy.'],
  flowchart:['Purpose: communicate the order of steps and decisions in a process. Know the inputs, required outputs and rules before drawing it.','Use a terminator for Start/End, rectangles for processes, parallelograms for input/output and diamonds for decisions. Flow lines have arrows; decision exits need clear labels.','Advantage: tracing a route can expose missing steps or incorrect logic before coding. Limitation: a large, tangled flowchart becomes difficult to follow and maintain.','A flowchart plans behaviour; it does not specify the appearance of a poster or screen. Presentation or diagramming software can create the symbols and connections.'],
  visualisation:['Purpose: show how a static product will look. Include layout, headings, text, image positions and annotation specifying colour, font and size.','Use it to plan a flyer, leaflet, poster or webpage appearance. It does not show the timing of a video sequence.','Advantage: stakeholders can discuss the intended appearance before production. Limitation: vague annotations leave room for different interpretations.','DTP or image-editing software can position and align elements. A plan communicates the intention; it does not prove that interactive features work.'],
  wireframe:['Purpose: plan the structure and layout of a screen, including navigation and interactivity where relevant. Use labelled boxes and image placeholders.','A wireframe usually prioritises content placement over decorative details. Labels can show where a button leads without making it functional.','Advantage: early feedback can reveal missing content or confusing navigation before development. Limitation: a wireframe alone cannot confirm technical feasibility.','Presentation software, drawing tools or specialist wireframing software can be used. Do not spend so long styling the plan that the basic structure is overlooked.'],
  moodboard:['Purpose: communicate a proposed theme through images, colours, typography, textures and keywords.','Choose inspiration suited to the target audience and explain how the choices fit the purpose. It is a collection of inspiration rather than a finished product.','Advantage: a shared mood board helps a team discuss a consistent visual direction. Limitation: it does not specify precise element positions, screen navigation or process logic.','Presentation or image-editing software can assemble the collection. Record sources for any third-party imagery and use material you have permission to use.']};return <GlossaryContent><div>{notes[tool].map((n,i)=><p key={i}>{n}</p>)}</div></GlossaryContent>;}
export default function ResourcesPage(){const [params,setParams]=useSearchParams();const requested=params.get('tool');const tool:ProjectTool=requested && Object.keys(toolNames).includes(requested)?requested as ProjectTool:'mindmap';const setTool=(t:ProjectTool)=>setParams({tool:t});return <div className="page"><h1>Visual examples and resources</h1><p>Original teaching examples. Compare a plan with a product, then try your own design.</p><label>Design tool<select className="text-input" value={tool} onChange={e=>setTool(e.target.value as ProjectTool)}>{Object.entries(toolNames).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><LearningResources key={tool} tool={tool}/><details className="read-more"><summary>Check this topic: five R050-style MCQs</summary><ExamPractice key={tool} tool={tool}/></details><details className="card card-pad"><summary>Product gallery: leaflet, flyer and poster</summary><div className="resource-pair"><figure><Flyer/><figcaption>A flyer: a compact promotional sheet.</figcaption></figure><figure><div className="leaflet-example" role="img" aria-label="Three-panel school club leaflet: welcome, activities, and how to join"><section><h3>FIND YOUR CLUB</h3><p>Try something new this term.</p><strong>Example School</strong></section><section><h3>EXPLORE</h3><p>Music · Coding · Sport</p><p>Build skills and meet new people.</p></section><section><h3>JOIN IN</h3><p>Ask your tutor for club times.</p><p>Choose a club. Attend a taster. Get involved.</p></section></div><figcaption>A leaflet: several panels organise more information.</figcaption></figure><figure><div className="poster-example" role="img" aria-label="Original school library poster: Read something new. Visit the library at lunchtime."><small>YOUR NEXT STORY STARTS HERE</small><h3>READ<br/>SOMETHING<br/>NEW.</h3><p>Visit the library at lunchtime.</p></div><figcaption>A poster: a large, brief message for display.</figcaption></figure></div></details></div>;}
